<a href="https://colab.research.google.com/github/KoushikDas161/ATM-Machine-System-using-singleton/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy- Numerical Python

Advantages of Numpy Arrays:

1. Allows several mathematical operations

2. Faster operations

# New Section

In [1]:
import numpy as np

In [9]:
np_array = np.array([1, 2, 3, 4,5])
print(np_array)

[1 2 3 4 5]


In [3]:
type(np_array)

numpy.ndarray

In [5]:
type(np_array)

numpy.ndarray

In [7]:
b = np.array([(1, 2, 3,7), (4, 5, 6,8),(3,5,6,7)])
print(b)

[[1 2 3 7]
 [4 5 6 8]
 [3 5 6 7]]


In [10]:
print(b.shape)

(3, 4)


In [12]:
new= b.reshape(4,3)

In [ ]:
new

In [13]:
print(new.shape)

(4, 3)


In [14]:
type(b)

numpy.ndarray

In [15]:

print(b.ndim)

2


In [21]:
c = np.array([(1, 2), (3, 4), (1, 5)], dtype=int )
print(c)

[[1 2]
 [3 4]
 [1 5]]


create a numpy arrays of zeros

In [23]:
z = np.zeros((4, 7))
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [33]:
a = np.ones((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
#create array of particular values
a = np.full((3, 4), 5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [35]:
#create an identity matrix
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
#create a numpy array with random values
r = np.random.random((3, 4))
print(r)

[[0.94926771 0.65156401 0.92009911 0.44354854]
 [0.99589482 0.07947859 0.89091013 0.97368356]
 [0.49895715 0.87574464 0.79530481 0.55461264]]


In [43]:
#create a numpy array of random integer (randint) values within a specific range
s = np.random.randint(10, 100, (3, 9))
print(s)

[[13 68 37 58 33 35 49 14 63]
 [14 81 73 93 56 45 76 46 83]
 [64 93 61 42 43 48 53 81 90]]


In [45]:
#create array of evenly spaced values (specifying the number of values)
d = np.linspace(10, 30, 17)
print(d)

[10.   11.25 12.5  13.75 15.   16.25 17.5  18.75 20.   21.25 22.5  23.75
 25.   26.25 27.5  28.75 30.  ]


In [49]:
#array of evenly spaced values (specifying the steps)
e = np.arange(10, 30, 1)
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [52]:
list2 = [1, 2, 4, 5,6]

a = np.asarray(list2)
print(a)
type(a)

[1 2 4 5 6]


numpy.ndarray

In [53]:
c = np.random.randint(10, 50, (4, 4))
print(c)

[[13 15 39 10]
 [14 27 44 45]
 [47 10 18 11]
 [41 41 38 39]]


In [54]:
#number of rows and columns
print(c.shape)

(4, 4)


In [55]:
print(c.ndim)

2


In [56]:
#number of elements in array
print(c.size)

16


In [70]:
a = np.random.randint(0,100, (3,3))
b = np.random.randint(10, 20, (3, 3))
print(a)
print(b)

[[ 1 58 93]
 [46 31 51]
 [20 25 67]]
[[19 12 16]
 [13 16 18]
 [19 19 10]]


In [71]:
print(a+b)

[[ 20  70 109]
 [ 59  47  69]
 [ 39  44  77]]


In [72]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 20  70 109]
 [ 59  47  69]
 [ 39  44  77]]
[[-18  46  77]
 [ 33  15  33]
 [  1   6  57]]
[[  19  696 1488]
 [ 598  496  918]
 [ 380  475  670]]
[[0.05263158 4.83333333 5.8125    ]
 [3.53846154 1.9375     2.83333333]
 [1.05263158 1.31578947 6.7       ]]


In [73]:
a = np.random.randint(0, 10, (2, 3))
print(a)

[[3 3 8]
 [0 0 3]]


In [75]:
#transpose
t = np.transpose(a)
t1 = a.T
print(t)
print(t.shape)
print(t1)

[[3 0]
 [3 0]
 [8 3]]
(3, 2)
[[3 0]
 [3 0]
 [8 3]]


In [76]:
print(a)

[[3 3 8]
 [0 0 3]]


In [80]:
#reshaping array
b= a.reshape(3, 2)
t= a.T
print(b)
print(t)
print(b.shape)
print(t.shape)

[[3 3]
 [8 0]
 [0 3]]
[[3 0]
 [3 0]
 [8 3]]
(3, 2)
(3, 2)
